---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-220-acc
  labels:
    heritage: example-220
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: example-220
  labels:
    heritage: example-220
rules:
- apiGroups: ["stable.example.com"]
  resources: ["crontabs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: example-220
  labels:
    heritage: example-220
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-220
subjects:
  - kind: ServiceAccount
    name: example-220-acc
    namespace: {{ .Release.Namespace }}
