image: registry.gitlab.com/ch-tbz-hf/stud/cnt/workspace-full:latest

tasks:
  - command: |
      echo "$WG_CONFIG"  | base64 -d > /workspace/.wg-config.conf
      echo "$K8S_CONFIG" | base64 -d > ~/.kube/config
      wg-quick up /workspace/.wg-config.conf
